services:
    app.installer:
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\AppInstaller
        tags:
            - { name: ezplatform.installer, type: practical-apis }

    app.ipa_service:
        class: 'AppBundle\Service\IpaService'
        arguments: ['@ezpublish.api.service.content', '@ezpublish.fieldType.ezimage.variation_service']

    app.ezrest.value_visitor.ipa:
        parent: ezpublish_rest.output.value_object_visitor.base
        class: "AppBundle\Visitor\Ipa"
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: AppBundle\Entity\Ipa }

    app.ezrest.value_visitor.brewery:
        parent: ezpublish_rest.output.value_object_visitor.base
        class: "AppBundle\Visitor\Brewery"
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: AppBundle\Entity\Brewery }

    app.richtext.converter.reducer:
        class: "AppBundle\Service\RichTextReducer"
        arguments:
            - "@ezpublish.fieldType.ezrichtext.renderer"
            - "@ezpublish.api.service.content"
        tags:
            - {name: ezpublish.ezrichtext.converter.output.xhtml5, priority: 5}