services:
    app.installer:
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\AppInstaller
        tags:
            - { name: ezplatform.installer, type: practical-apis }

    app.ipa_service:
        class: 'AppBundle\Service\IpaService'
        arguments: ['@ezpublish.api.service.content']


    app.matcher.representation:
        class: 'AppBundle\Matcher\Representation'

