services:
    app.installer:
        parent: ezplatform.installer.db_based_installer
        class: AppBundle\Installer\AppInstaller
        tags:
            - { name: ezplatform.installer, type: practical-apis }

    app.ipa_service:
        class: 'AppBundle\Service\IpaService'
        arguments: ['@ezpublish.api.service.content', '@ezpublish.fieldType.ezimage.variation_service']

    app.ezrest.value_visitor:
        parent: ezpublish_rest.output.value_object_visitor.base
        class: "AppBundle\Visitor\Ipa"
        tags:
            - { name: ezpublish_rest.output.value_object_visitor, type: AppBundle\Entity\Ipa }